[package]
name = "watsoncli"
version = "0.1.0"
authors = ["Jan Schulte <hello@unexpected-co.de>"]

[dependencies]
clap = "2.31.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
notify = "4.0.0"
